### POST request to create new artist
POST http://localhost:8080/api/artists
accept: */*
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com"
}
###

### POST request to create new artist
POST http://localhost:8080/api/artists
accept: */*
Content-Type: application/json

{
  "name": "Bob Roberts",
  "email": "bob.roberts@example.com"
}
###

### POST request to create new artist
POST http://localhost:8080/api/artists
accept: */*
Content-Type: application/json

{
  "name": "Charlie Charles",
  "email": "charlie.charles@example.com"
}
###

### POST request to create new artist
POST http://localhost:8080/api/artists
accept: */*
Content-Type: application/json

{
  "name": "Delete Me",
  "email": "delete.me@example.com"
}
###

### PUT request to update existing artist
PUT http://localhost:8080/api/artists/2
accept: */*
Content-Type: application/json

{
  "id": 2,
  "name": "Bob Robertson",
  "email": "bob.robertson@example.com"
}
###

### GET request to retrieve artist by ID
GET http://localhost:8080/api/artists/2
accept: */*
###

### DELETE request to delete existing artist
DELETE http://localhost:8080/api/artists/4
accept: */*
###

### GET request to retrieve all artists
GET http://localhost:8080/api/artists
accept: */*
###
